apiVersion: v1
kind: Service
metadata:
  name: payment-app
  namespace: payment-dev
spec:
  selector:
    app: payment-app
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: payment-dev
spec:
  selector:
    app: postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
